### ISSUE TITLE
things to do

### ISSUE THREAD

**Issue by gouku13** [gouku13/gearswap#6]
note to self   i never checked if the sch SC but curing it thing was thinged
and i also need to add gear changing buffs light arts or dark arts for midcast enfeebling fml

**Comment by gouku13** [comment]
also jesus christ jonie's enfeebling set needs an overhaul

**Comment by ibm2431** [comment]
> never checked if the sch SC but curing it thing was thinged

It was not, but I just pushed to fix.

> gear changing buffs light arts or dark arts for midcast enfeebling

I was in the middle of typing how this would be done, but realized Visual Studio was still open and it'd be quicker to just add and push. [Check `job_specific_midcast` for Jackii_SCH. I have the sets named Light_Stuff and Dark_Stuff, so you can rename/define them however you want.](https://github.com/gouku13/gearswap/commit/fbb8d81ab4d429c6525a6b5115933dc86bbd668e)

I didn't know if they needed to be separate for Light/Dark, or if the same gear works for both. If the same gear works for both, just remove the inner `if buffactive['Light Arts']` and `if buffactive['Dark Arts']` checks and replace them with a single equip like `set_combine(sets.Enfeebling, sets.Art_Enhance)` or something.
